module.exports = {
  A: "S No",
  B: "accountNumber",
  C: "firstName",
  D: "spouseName",
  E: "address",
  F: "gender",
  G: "loanReferenceNumber",
  H: "kccAccountNumber",
  I: "surveyNo",
  J: "khataDetails",
  K: "plotNo",
  L: "village",
  M: "zone",
  N: "pincode",
  O: "landArea",
  P: "mortageDetails",
  Q: "mobileNumber",
  R: "bankBranchCode",
  S: "district"
}