module.exports = {
  A1: "S.No",
  A2: "firstName", 
  A3: "lastName",
  A4: "gender",
  A5: "dob",
  A6: "emailId",
  A7: "mobileNumber",
  A8: "spouseName",
  A9: "accountNumber",
  A10: "loanReferenceNumber",
  A11: "kccAccountNumber",
  A12: "landArea",
  A13: "village",
  A14: "district",
  A15: "pincode",
  A16: "address",
}