const USER_TYPE = {
	PATIENT: 'PATIENT',
	ADMIN: 'ADMIN',
	DOCTOR: 'DOCTOR'
};

const USER_STATUS = {
	APPROVED:'APPROVED',
	REJECTED:'REJECTED',
	ACTIVE: 'ACTIVE',
	INACTIVE: 'INACTIVE',
	DELETED: 'DELETED'
};

const ADDRESS_STATUS = {
	'ACTIVE': 'ACTIVE',
	'DELETED': 'DELETED'
};

const S3_FOLDER_NAME = {
	LAND_RECORDS: 'land-records',
	LAND_REPORTS: 'land-reports'
};

const DATA_STATUS = {
	ACTIVE: 0,
	DELETED: 1
}

const SEARCH_TYPE = {
	NORMAL: 0,
	DROPDOWN: 1
}

const SEARCH_HEADERS = {
	BANK_BRANCH_CODE: 0,
	CIF_ACCOUNT_NUMBER: 1,
	SURVEY_NUMBER: 2,
	VILLAGE_NAME: 3,
	MANDAL_NAME: 4,
	DISTRICT_NAME: 5,
	KCC_ACCOUNT_NUMBER: 6,
	COMMENTS: 7
}
const SEARCH_HEADERS_CROP = {
	STATE: 0,
	DISTRICT: 1,
	MANDAL: 2,
	VILLAGE: 3,
	CADASTRAL_NUMBER: 4,
	VILLA_CAD: 5,
	CROP_NAME: 6,
	CROP_TYPE: 7
}
const SEARCH_HEADERS_USER = {
	NAME: 0,
	EMAIL: 1
}
const SEARCH_HEADERS_ADMIN_USER = {
	NAME: 0,
	ROLE: 1,
	EMAIL:2,
	BRANCH_CODE:3,
	MOBILE:4,
}

const COMMENT_RESOLUTION = {
	NOT_RESOLVED: 0,
	RESOLVED: 1,
	NEW_COMMENT: 2
}

module.exports = {
	USER_TYPE,
	USER_STATUS,
	ADDRESS_STATUS,
	S3_FOLDER_NAME,
	DATA_STATUS,
	SEARCH_TYPE,
	SEARCH_HEADERS,
	SEARCH_HEADERS_CROP,
	SEARCH_HEADERS_USER,
	SEARCH_HEADERS_ADMIN_USER,
	COMMENT_RESOLUTION
}